'use strict';

const ptToLevel = {
        "Bauchbänder": "Level 1",
        "Netztelefon": "Level 5",
        "Babybadetuch": "Level 1",
        "Babybadewanne": "Level 1",
        "Babyflasche": "Level 1",
        "Babyflasche Zubehör": "Level 1",
        "Babykörperpflege": "Level 1",
        "Babynahrungsbehälter": "Sondertaetigkeit",
        "Babynahrungszubereiter": "Sondertaetigkeit",
        "Babyphone": "Level 6",
        "Babyphone Zubehör": "Level 1",
        "Babytrage": "Level 1",
        "Beissring": "Sondertaetigkeit",
        "Feuchttücher": "Level 1",
        "Flaschensauger": "Level 1",
        "Flaschenwärmer": "Sondertaetigkeit",
        "Kindergeschirr + Kinderbesteck": "Level 1",
        "Kinderschemel": "Level 1",
        "Kindersitz": "Sondertaetigkeit",
        "Kindersitz Zubehör": "Level 1",
        "Kinderwagen": "Level 1",
        "Kinderwagen Fusssack": "Level 1",
        "Kinderwagen Zubehör": "Level 1",
        "Kinderwagenspielzeug": "Level 1",
        "Lätzchen": "Level 1",
        "Mamapflege": "Level 1",
        "Milchpumpe": "Sondertaetigkeit",
        "Milchpumpe Zubehör": "Sondertaetigkeit",
        "Nasensauger": "Sondertaetigkeit",
        "Nuggi": "Sondertaetigkeit",
        "Nuggi Zubehör": "Level 1",
        "Pflegekorb": "Level 1",
        "Pucktuch + Nuscheli": "Level 1",
        "Schwimmwindeln": "Sondertaetigkeit",
        "Sterilisator": "Level 1",
        "Stilleinlagen": "Level 1",
        "Stillhütchen": "Level 1",
        "Toilettentrainer": "Level 1",
        "Töpfchen": "Sondertaetigkeit",
        "Tragetuch": "Level 1",
        "Tragewanne + Babykorb": "Level 1",
        "Wickeltasche": "Level 1",
        "Wickeltisch Heizstrahler": "Level 1",
        "Windeleimer": "Level 1",
        "Windeleinlagen": "Level 1",
        "Windeln": "Sondertaetigkeit",
        "After Sun": "Level 1",
        "Aftershave": "Level 1",
        "Analdusche": "Level 1",
        "Analtoy": "Level 1",
        "Arzneimittel": "Level 1",
        "Ätherische Öle": "Level 1",
        "Augenbrauenfarbe": "Level 1",
        "Augenbrauengel": "Level 1",
        "Augenbrauenpuder": "Level 1",
        "Augenbrauenstift": "Level 1",
        "Augenpflege": "Level 1",
        "Augentropfen": "Level 1",
        "Badezubehör": "Level 1",
        "Badezusatz": "Level 1",
        "Bandage": "Level 1",
        "Bartpflege": "Level 1",
        "BB + CC Creme": "Level 1",
        "BDSM Zubehör": "Level 1",
        "Beauty Geschenkset": "Level 1",
        "Beckenbodentrainer": "Level 1",
        "Bettflasche": "Level 1",
        "Binden": "Level 1",
        "Bleaching": "Sondertaetigkeit",
        "Blush": "Level 1",
        "Bodylotion": "Level 1",
        "Bodyspray + Hair Mist": "Level 1",
        "Brillengestell": "Level 1",
        "CBD Öl": "Level 1",
        "Computerbrille": "Level 1",
        "Concealer": "Level 1",
        "Conditioner": "Level 1",
        "Deo": "Level 1",
        "Desinfektionsmittel": "Level 1",
        "Desinfektionsmittelspender": "Level 1",
        "Dessous": "Level 1",
        "Dildo": "Sondertaetigkeit",
        "Duschmittel": "Level 1",
        "Erotikspiel": "Level 1",
        "Erste Hilfe Set": "Sondertaetigkeit",
        "Eyeliner + Kajal": "Level 1",
        "Farbige Linsen": "Level 1",
        "Fetischkleider": "Sondertaetigkeit",
        "Fusspflegemittel": "Level 1",
        "Gehhilfe": "Level 1",
        "Gesichtscreme": "Level 1",
        "Gesichtsmaske": "Sondertaetigkeit",
        "Gesichtspuder": "Sondertaetigkeit",
        "Gesichtsreinigung": "Level 1",
        "Gesichtsserum": "Sondertaetigkeit",
        "Gleitmittel": "Level 1",
        "Haarband + Haarreif": "Level 1",
        "Haarbürste + Kamm": "Level 1",
        "Haarfarbe": "Level 1",
        "Haargel + Haarwachs": "Level 1",
        "Haargummi": "Level 1",
        "Haarklammer + Haarclips": "Level 1",
        "Haarmaske": "Level 1",
        "Haaröl + Haarserum": "Level 1",
        "Haarschaum": "Level 1",
        "Haarschere": "Level 1",
        "Haarschmuck": "Level 1",
        "Haarspray": "Level 1",
        "Hair Extensions": "Level 1",
        "Handcreme": "Level 1",
        "Handseife": "Level 1",
        "Handzahnbürste": "Level 1",
        "Highlighter + Bronzer": "Level 1",
        "Inkontinenzhygiene": "Level 1",
        "Insektenschutzmittel": "Level 1",
        "Interdentalbürste": "Level 1",
        "Intimpflege": "Sondertaetigkeit",
        "Kinesio Tape": "Level 1",
        "Kondom": "Level 1",
        "Kontaktlinsen": "Level 1",
        "Kopfhautpflege": "Sondertaetigkeit",
        "Künstliche Wimpern": "Level 1",
        "Lesebrille": "Level 1",
        "Lidschatten": "Level 1",
        "Liebeskugeln": "Sondertaetigkeit",
        "Linsenmittel": "Level 1",
        "Lipliner": "Level 1",
        "Lippenpflege": "Level 1",
        "Lippenstift + Lipgloss": "Level 1",
        "Lockenwickler": "Level 1",
        "Love Box": "Level 1",
        "Magenmittel + Darmmittel": "Level 1",
        "Mascara": "Level 1",
        "Massageöl": "Level 1",
        "Masturbator": "Sondertaetigkeit",
        "Medikamentenbox": "Level 1",
        "Menstruationstasse": "Level 1",
        "Mundpflege": "Sondertaetigkeit",
        "Mundschutz": "Level 1",
        "Mundschutz Zubehör": "Level 1",
        "Mundspülung": "Level 1",
        "Muskelsalbe + Kühlpad": "Level 1",
        "Nagellack": "Level 1",
        "Nagellackentferner": "Level 1",
        "Nagelpflegemittel": "Level 1",
        "Nagelstyling + Kunstnägel": "Level 1",
        "Nasenpflege + Rachenpflege": "Sondertaetigkeit",
        "Nassrasierer": "Level 1",
        "Nierenmittel + Blasenmittel": "Level 1",
        "Ohrenpflege": "Level 1",
        "Parfum": "Sondertaetigkeit",
        "Penishülle": "Sondertaetigkeit",
        "Peniskäfig": "Sondertaetigkeit",
        "Penisplug": "Sondertaetigkeit",
        "Penispumpe": "Sondertaetigkeit",
        "Penisring": "Sondertaetigkeit",
        "Periodenunterwäsche": "Sondertaetigkeit",
        "Pflaster": "Level 1",
        "Pinzette": "Level 1",
        "Praxisbedarf": "Level 1",
        "Primer + Base": "OVP",
        "Rasierhobel + Rasiermesser": "Sondertaetigkeit",
        "Rasierklingen": "Sondertaetigkeit",
        "Rasierschaum + Rasiergel": "Level 1",
        "Reizwäsche BH": "Level 1",
        "Reizwäsche Slip": "Level 1",
        "Salonbedarf": "Level 1",
        "Schminkpinsel": "Level 1",
        "Schwangerschaftstest": "Sondertaetigkeit",
        "Selbstbräuner": "Level 1",
        "Selbsttest": "Sondertaetigkeit",
        "Senioren Alltagshilfe": "Level 1",
        "Sexmaschine": "Sondertaetigkeit",
        "Sexmöbel": "Sondertaetigkeit",
        "Sexpuppe": "Sondertaetigkeit",
        "Shampoo": "Level 1",
        "Sonnencreme": "Level 1",
        "Stimulationsmittel": "Level 1",
        "Strapse": "Level 1",
        "Tampons": "Sondertaetigkeit",
        "Taschentücher + Kosmetiktücher": "Level 1",
        "Toy Cleaner": "Level 1",
        "Vaginapumpe": "Sondertaetigkeit",
        "Verbandsmaterial": "Level 1",
        "Vibrator": "Sondertaetigkeit",
        "Wachs + Enthaarungscreme": "Level 1",
        "Wattepads": "Level 1",
        "Wattestäbchen": "Level 1",
        "Wimpernserum": "Level 1",
        "Wundversorgung": "Level 1",
        "Zahnpasta": "Level 1",
        "Zahnseide": "Level 1",
        "Zubehör Make-up": "Level 1",
        "Zubehör Sex Toys": "Sondertaetigkeit",
        "Zungenreiniger": "Sondertaetigkeit",
        "Anzüge": "Level 1",
        "Armlinge + Beinlinge": "Level 1",
        "Babyschuhe": "Level 1",
        "Badeanzüge": "Level 1",
        "Badehosen": "Level 1",
        "Badeschuhe": "Level 1",
        "Badeshirts": "Level 1",
        "Ballerinas": "Level 1",
        "Bauchtasche": "Level 1",
        "BHs": "Level 1",
        "Bikinis": "Level 1",
        "Blusen": "Level 1",
        "Bodys": "Level 1",
        "Boots + Stiefel": "Level 1",
        "Brillen Zubehör": "Level 1",
        "Brillenetui": "Level 1",
        "Brillenkette": "Level 1",
        "Cap": "Level 1",
        "Einkaufshilfe": "Level 1",
        "Eishockeytrikot": "Level 1",
        "Espadrilles": "Level 1",
        "Fitnesshandschuhe": "Level 1",
        "Flip-Flops": "Level 1",
        "Funktionsshirt": "Level 1",
        "Funktionsunterhose": "Level 1",
        "Fussballschuhe": "Level 1",
        "Fussballtrikot": "Level 1",
        "Gamaschen": "Level 1",
        "Gesundheitsschuhe": "Level 1",
        "Golfschuhe": "Level 1",
        "Gummistiefel": "Level 1",
        "Gürtel": "Level 1",
        "Halbschuhe": "Level 1",
        "Hallenschuhe": "Level 1",
        "Handschuhe": "Level 1",
        "Handtasche": "Level 1",
        "Hausschuhe": "Level 1",
        "Hemden": "Level 1",
        "Hosen": "Level 1",
        "Hut": "Level 1",
        "Jeans": "Level 1",
        "Jumpsuits": "Level 1",
        "Kindergartentasche": "Level 1",
        "Kleider": "Level 1",
        "Kletterhandschuhe": "Level 1",
        "Kletterschuhe": "Level 1",
        "Koffer": "Level 1",
        "Krawatte + Fliege": "Level 1",
        "Langlaufhose": "Level 1",
        "Langlaufjacke": "Level 1",
        "Laufjacke": "Level 1",
        "Laufschuhe": "Level 1",
        "Leichte Jacken": "Level 1",
        "Mäntel": "Level 1",
        "Mütze": "Level 1",
        "Necessaire": "Level 1",
        "Outdoorhose": "Level 1",
        "Outdoorjacken": "Level 1",
        "Packsack": "Level 1",
        "Portemonnaie": "Level 1",
        "Pullover": "Level 1",
        "Pumps": "Level 1",
        "Pyjamas": "Level 1",
        "Regenjacken": "Level 1",
        "Regenschirm": "Level 1",
        "Reisehandtuch": "Level 1",
        "Reisezubehör": "Level 1",
        "Reiter Oberbekleidung": "Level 1",
        "Reithandschuhe": "Level 1",
        "Reithelm": "Level 1",
        "Reithose": "Level 1",
        "Reitstiefel": "Level 1",
        "Röcke": "Level 1",
        "Rucksack": "Level 1",
        "Sandalen": "Level 1",
        "Schal": "Level 1",
        "Schlüsselanhänger": "Level 1",
        "Schnürsenkel": "Level 1",
        "Schuhüberzug": "Level 1",
        "Schweissband": "Level 1",
        "Shirts": "Level 1",
        "Shorts": "Level 1",
        "Skihandschuhe": "Level 1",
        "Skihosen": "Level 1",
        "Skijacke": "Level 1",
        "Sneakers": "Level 1",
        "Socken": "Level 1",
        "Sonnenbrille": "Level 1",
        "Sport-BH": "Level 2",
        "Sporthose": "Level 1",
        "Sportshirt": "Level 1",
        "Sportsocken": "Level 1",
        "Still-BHs": "Level 1",
        "Stillshirts + Stillkleider": "Level 1",
        "Stirnband": "Level 1",
        "Strampler": "Level 1",
        "Strümpfe": "Level 1",
        "Sturmhaube + Halsschlauch": "Level 1",
        "Tanzschuhe": "Level 1",
        "Tasche": "Level 1",
        "Tennisschuhe": "Level 1",
        "Tights": "Level 1",
        "Tragejacken": "Level 1",
        "Trainingsjacken": "Level 1",
        "Unterhosen": "Level 1",
        "Velohandschuhe": "Level 1",
        "Velohosen": "Level 1",
        "Velojacke": "Level 1",
        "Veloschuhe": "Level 1",
        "Veloschuhe Zubehör": "Level 1",
        "Velotrikot": "Level 1",
        "Wanderschuhe": "Level 1",
        "Westen": "Level 1",
        "Winterjacken": "Level 1",
        "Agenda": "Level 1",
        "Bastelpapier": "Level 1",
        "Beschriftungsband": "Level 1",
        "Bleistift": "Level 1",
        "Bleistiftminen": "Level 1",
        "Briefumschlag": "Level 1",
        "Buchfolie": "Level 1",
        "Büroklammer": "Level 1",
        "Cutter": "Level 1",
        "Dokumentenablage": "Level 1",
        "Druckerpatrone": "Level 1",
        "Ersatzpatronen + Tintenfass": "Level 1",
        "Etiketten": "Level 1",
        "Etui": "Level 1",
        "Formular": "Level 1",
        "Fotokleber + Posterkleber": "Level 1",
        "Fotopapier": "Level 1",
        "Geschenkverpackung": "Level 1",
        "Grusskarte + Briefpapier": "Level 1",
        "Gummiband": "Level 1",
        "Haftnotiz": "Level 1",
        "Heft + Block": "Level 1",
        "Heftgerät": "Level 1",
        "Informationsschild": "Level 1",
        "Kalender": "Level 1",
        "Karteikarten": "Level 1",
        "Kartenaufbewahrung": "Level 1",
        "Keilrahmen": "Level 1",
        "Klebebandabroller": "Level 1",
        "Kleberoller": "Level 1",
        "Klebestift": "Level 1",
        "Kopierpapier": "Level 1",
        "Korrekturmittel": "Level 1",
        "Lieferscheintasche": "Level 1",
        "Lineal": "Level 1",
        "Locher": "Level 1",
        "Magnet": "Level 1",
        "Malbuch": "Level 1",
        "Malstifte": "Level 1",
        "Mappe": "Level 1",
        "Marker": "Level 1",
        "Optische Medien Zubehör": "Level 1",
        "Optischer Datenträger": "Level 1",
        "Ordner": "Level 1",
        "Ordner Zubehör": "Level 1",
        "Plotterpapier": "Level 1",
        "Prospektständer": "Level 1",
        "Schere": "Level 1",
        "Schreibstifte": "Level 1",
        "Schultüte": "Level 1",
        "Spitzer": "Level 1",
        "Staffelei": "Level 1",
        "Stempel": "Level 1",
        "Sticker": "Level 1",
        "Thermopapierrolle": "Level 1",
        "Toner": "Level 1",
        "Unterlage": "Level 1",
        "Verpackungsmaterial": "Level 1",
        "Versandkarton + Versandbox": "Level 1",
        "Versandtasche + Luftpolstertasche": "Level 1",
        "Zirkel": "Level 1",
        "Zubehör Präsentieren": "Level 1",
        "Akkordeon": "Level 1",
        "Antennenkabel": "Level 1",
        "Audio Adapter": "Level 1",
        "Audio Interface": "Level 1",
        "Audio Racks + Cases": "Level 1",
        "Audio Stecker": "Level 1",
        "Audio Zubehör": "Level 1",
        "Audiokabel": "Level 1",
        "Audiorecorder": "Level 6",
        "AV Receiver": "Level 1",
        "Beamer": "Level 6",
        "Beamer Halterung": "Level 1",
        "Beamer Zubehör": "Level 1",
        "Beamerlampe": "Level 1",
        "Becken": "Level 1",
        "Blasinstrument Zubehör": "Sondertaetigkeit",
        "Blasinstrumente": "Sondertaetigkeit",
        "Bluetooth Audio Adapter": "Level 1",
        "Bluetooth Lautsprecher": "Level 1",
        "Bluray Player + DVD Player": "Level 6",
        "CD- & Schallplatten Aufbewahrung": "Level 1",
        "CI Modul + Pay TV": "Level 1",
        "Diktiergerät": "Level 6",
        "Diktiergerät Zubehör": "Level 1",
        "Diverse Kabel": "Level 1",
        "DJ Cases": "Level 1",
        "DJ Controller": "Level 1",
        "DJ Möbel": "Level 1",
        "DJ Wiedergabegerät": "Level 1",
        "Drumhead": "Level 1",
        "Drumsticks + Schlägel": "Level 1",
        "Effektgerät": "Level 1",
        "Effektpedal": "Level 1",
        "Einbaulautsprecher": "Level 1",
        "Fernbedienung": "Level 1",
        "Firewire Kabel": "Level 1",
        "Gitarre": "Level 1",
        "Gitarre Zubehör": "Level 1",
        "Hazer": "Level 1",
        "HiFi + Heimkino Lautsprecher": "Level 1",
        "HiFi Komponente": "Level 1",
        "Instrumentenständer + Halter": "Level 1",
        "Instrumententasche + Koffer": "Level 1",
        "Instrumentenverstärker": "Level 1",
        "Kabel Zubehör": "Level 1",
        "Keyboard": "Level 1",
        "Kopfhörer": "Level 1",
        "Kopfhörer Ersatzteile": "Level 1",
        "Kopfhörerständer": "Level 1",
        "Kopfhörertasche + Schutzhülle": "Level 1",
        "Kopfhörerverstärker": "Level 1",
        "Lautsprecher Bausatz": "Level 1",
        "Lautsprecher Bauteile": "Level 1",
        "Lautsprecher Ständer + Wandmontage": "Level 1",
        "Lautsprecherbau Zubehör": "Level 1",
        "Lautsprecherkabel": "Level 1",
        "Leinwand": "Level 1",
        "Leinwand Zubehör": "Level 1",
        "Lichtsteuerung": "Level 1",
        "Lichttechnik Leuchtmittel": "Level 1",
        "Lichttechnik Zubehör": "Level 1",
        "LNB": "Level 1",
        "MIDI Controller": "Level 1",
        "Mikrofon": "Level 1",
        "Mikrofon Popschutz": "Level 1",
        "Mikrofon Windschutz": "Level 1",
        "Mikrofon Zubehör": "Level 1",
        "Mikrofonspinne": "Level 1",
        "Mikrofonständer": "Level 1",
        "Mischpult": "Level 1",
        "Monitor Lautsprecher": "Level 1",
        "Montage Lichttechnik": "Level 1",
        "MP3 + Media-Player Zubehör": "Level 1",
        "MP3 Player + Portable Audiogeräte": "Level 6",
        "MP3 Tasche + Hülle": "Level 1",
        "Multiroom System": "Level 1",
        "Nebelmaschine": "Level 1",
        "Notenständer": "Level 1",
        "PA Lautsprecher": "Level 1",
        "Perkussion": "Level 1",
        "Phono Vorverstärker": "Level 1",
        "Plattenspieler": "Level 1",
        "Plattenspieler Zubehör": "Level 1",
        "Plektrum": "Level 1",
        "Radio": "Level 1",
        "Raumakustik": "Level 1",
        "Recording Zubehör": "Level 1",
        "Saiten": "Level 1",
        "SAT Spiegel + SAT Antennen": "Level 1",
        "SAT Zubehör": "Level 1",
        "Scheinwerfer": "Level 1",
        "Schlagzeug": "Level 1",
        "Schlagzeug Zubehör": "Level 1",
        "Schnittstellenkabel": "Level 1",
        "Smart Speaker": "Level 1",
        "Soundbar": "Level 1",
        "Spiegelkugel": "Level 1",
        "Stereoanlage": "Level 1",
        "Stereoverstärker": "Level 1",
        "Stimmgerät": "Level 1",
        "Streaming Box": "Sondertaetigkeit",
        "Streichinstrument Zubehör": "Level 1",
        "Streichinstrumente": "Level 1",
        "Stromkabel": "Level 1",
        "Synthesizer": "Level 1",
        "Tasteninstrument Zubehör": "Level 1",
        "Tonabnehmer": "Level 1",
        "TV": "Sondertaetigkeit",
        "TV Halterung Zubehör": "Level 1",
        "TV Receiver Zubehör": "Level 1",
        "TV Ständer": "Level 1",
        "TV Wandhalterung": "Level 1",
        "TV Zubehör": "Level 1",
        "Ukulele": "Level 1",
        "Universalladegerät": "Level 1",
        "USB Kabel": "Level 1",
        "Video Converter": "Level 1",
        "Videokabel": "Level 1",
        "Visualizer": "Level 1",
        "Wireless Transmitter": "Level 1",
        "Zubehör DJ": "Level 1",
        "Zubehör Instrumente": "Level 1",
        "Abbruchhammer + Meisselhammer": "Level 1",
        "Abdeckmaterial": "Level 1",
        "Abdeckplane": "Level 1",
        "Absperrung": "Level 1",
        "Absturzsicherung": "Sondertaetigkeit",
        "Abzweigdose": "Level 1",
        "Aktor": "Level 5",
        "Anfahrschutz": "Level 1",
        "Anreisswerkzeug": "Level 1",
        "Anzuchttöpfe + Anzuchtschalen": "Level 1",
        "Anzündhilfe": "Level 1",
        "Arbeitshose": "Level 1",
        "Arbeitsjacke": "Level 1",
        "Arbeitsleuchte": "Level 1",
        "Arbeitsoberteil": "Level 1",
        "Atemschutzmaske": "Sondertaetigkeit",
        "Aussendekoration": "Level 1",
        "Axt + Beil": "Level 1",
        "Badewanne": "Level 1",
        "Badewannefaltwand": "Level 1",
        "Badewannensitz + Duschhocker": "Level 1",
        "Badmöbelset": "Level 1",
        "Bauschaum": "Level 1",
        "Baustromverteiler": "Level 1",
        "Beitel + Handhobel": "Level 1",
        "Belüftungsventilator": "Level 1",
        "Betätigungsplatte": "Level 1",
        "Bewässerungskugeln + Tonkegel": "Level 1",
        "Bewässerungssystem": "Level 1",
        "Bewegungsmelder": "Level 1",
        "Bidetarmatur": "Level 1",
        "Bits": "Level 1",
        "Blech": "Level 1",
        "Blumenerde": "Level 1",
        "Blumenstrauss": "Level 1",
        "Blumentopf": "Level 1",
        "Blumentopf Zubehör": "Level 1",
        "Bodenbelag": "Level 1",
        "Bodenheizung": "Level 1",
        "Bohrereinsatz": "Level 1",
        "Bohrmaschine + Akkuschrauber": "Level 1",
        "Bolzenschneider + Seitenschneider": "Level 1",
        "Brandbekämpfer": "Sondertaetigkeit",
        "Briefkasten": "Level 1",
        "Briefkasten Zubehör": "Level 1",
        "Brunnen + Gartenteich": "Level 1",
        "Christbaumständer": "Level 1",
        "Container": "Level 1",
        "Dekupiersäge + Bandsäge": "Level 1",
        "Detektor": "Level 1",
        "Dichtmittel": "Level 1",
        "Draht": "Level 1",
        "Drehkippbeschlag": "Level 1",
        "Drehmaschine": "Level 1",
        "Drehmomentschlüssel": "Level 1",
        "Druckluftaufsatz": "Level 1",
        "Dübel": "Level 1",
        "Dünger": "Level 1",
        "Duscharmatur + Badewannenarmatur": "Level 1",
        "Duschbrause": "Level 1",
        "Duschgleitstange + Brausehalter": "Level 1",
        "Duschkabine + Duschwand": "Level 1",
        "Duschrinne": "Level 1",
        "Duschrückwand": "Level 1",
        "Duschschlauch": "Level 1",
        "Duschsystem": "Level 1",
        "Duschwanne": "Level 1",
        "Einbruchschutz + Alarmanlage": "Level 1",
        "Elektroblechschere": "Level 1",
        "Elektrogrill": "Level 1",
        "Elektromotor": "Level 1",
        "Elektrowerkzeug Set": "Level 1",
        "Endoskopkamera": "Level 1",
        "Energiemessgerät": "Level 1",
        "Epoxidharz": "Level 1",
        "Fackel": "Level 1",
        "Fahne": "Level 1",
        "Farbroller": "Level 1",
        "Farbsprühsystem": "Level 1",
        "Fenstergriff": "Level 1",
        "Feuchtigkeitsmessgerät": "Level 1",
        "Feuerlöscher": "Sondertaetigkeit",
        "Feuerschale": "Level 1",
        "Fliegengitter": "Level 1",
        "Fördertechnik": "Level 1",
        "Fräse": "Level 1",
        "Fräser": "Level 1",
        "Führungsschiene": "Level 1",
        "Gartenbodenbelag": "Level 1",
        "Gartenbrause": "Level 1",
        "Gartencheminée": "Level 1",
        "Gartendusche": "Level 1",
        "Gartenhandwerkzeug": "Level 1",
        "Gartenhaus + Gartenschrank": "Level 1",
        "Gartenhaus Zubehör": "Level 1",
        "Gartenschere": "Level 1",
        "Gartenschlauch": "Level 1",
        "Gartenschlauch Aufbewahrung": "Level 1",
        "Gartenzaun": "Level 1",
        "Gasgrill": "Level 1",
        "Gefahrenmelder": "Level 1",
        "Gehörschutz": "Level 1",
        "Geldkassette": "Level 1",
        "Gewächshaus": "Level 1",
        "Gewindeschneider + Gewindebohrer": "Level 1",
        "Giesskanne": "Level 1",
        "Glas + Plexiglas": "Level 1",
        "Grillabdeckung": "Level 1",
        "Grillausstattung + Ersatzteile": "Level 1",
        "Grillbesteck": "Level 1",
        "Grillgeschirr": "Level 1",
        "Grillplatte": "Level 1",
        "Grillreinigungsutensil": "Level 1",
        "Grillrost": "Level 1",
        "Grillthermometer": "Level 1",
        "Growbox": "Level 1",
        "Haltegriff + Badewanneneinstiegshilfe": "Level 1",
        "Hammer": "Level 1",
        "Händetrockner": "Level 1",
        "Handkreissäge": "Level 1",
        "Handsäge": "Level 1",
        "Hausnummer + Türschild": "Level 1",
        "Hebehilfe": "Level 1",
        "Heckenschere": "Level 1",
        "Heissklebepistole": "Level 1",
        "Heisskleber": "Level 1",
        "Heissluftföhn": "Level 1",
        "Hobelmaschine": "Level 1",
        "Hochbeet": "Level 1",
        "Hochdruckreiniger": "Level 1",
        "Hochdruckreiniger Zubehör": "Level 1",
        "Hollywoodschaukel": "Level 1",
        "Holz": "Level 1",
        "Holzkohle": "Level 1",
        "Holzkohlegrill": "Level 1",
        "Holzschutz + Holzpflege": "Sondertaetigkeit",
        "Holzspalter + Häcksler": "Level 1",
        "Holzverbinder": "Level 1",
        "Indoor Growing Belüftung": "Level 1",
        "Indoor Growing Bewässerung": "Level 1",
        "Indoor Growing Zubehör": "Level 1",
        "Industriestaubsauger": "Level 1",
        "Industriestaubsauger Zubehör": "Level 1",
        "Infrarotthermometer": "Level 1",
        "Kabelbinder": "Level 1",
        "Kabelbox": "Level 1",
        "Kabeleinziehsystem": "Level 1",
        "Kabelhalter": "Level 1",
        "Kabelleitung": "Level 1",
        "Kabelrolle": "Level 1",
        "Kabelschutz + Kabelführung": "Level 1",
        "Kabelschutz + Kabelführung Zubehör": "Level 1",
        "Kabelverbindung": "Level 1",
        "Kabelverbindung Zubehör": "Level 1",
        "Kantenschutz + Schutzprofil": "Level 1",
        "Kappsäge + Gehrungssäge": "Level 1",
        "Kartuschenpistole + Fettpresse": "Level 1",
        "Kehrmaschine": "Level 1",
        "Kelle + Spachtel": "Level 1",
        "Kellerregal": "Level 1",
        "Keramikgrill": "Level 1",
        "Kette": "Level 1",
        "Kettensäge": "Level 1",
        "Klebeband": "Level 1",
        "Klebehaken + Klebenagel": "Level 1",
        "Klebstoff": "Level 1",
        "Klettband": "Level 1",
        "Klingel + Türsprechanlage": "Level 1",
        "Knieschutz": "Level 1",
        "Komposter + Gartensack": "Level 1",
        "Kompressor": "Level 1",
        "Kopfschutz": "Level 1",
        "Küchenarmatur": "Level 1",
        "Kugellager": "Level 1",
        "Künstlerfarbe + Bastelfarbe": "Level 1",
        "Kunstpflanzen": "Level 1",
        "Laborbedarf": "Level 1",
        "Lack": "Level 1",
        "Laderegler": "Level 1",
        "Lagerbehälter": "Level 1",
        "Längenmesswerkzeug": "Level 1",
        "Laserentfernungsmesser": "Level 1",
        "Laubsauger + Laubbläser": "Level 1",
        "Leiter + Gerüst": "Level 1",
        "Leiter + Gerüst Zubehör": "Level 1",
        "Leitungsführung": "Level 1",
        "Leitungsführung Zubehör": "Level 1",
        "Lichtschalter + Storenschalter": "Level 1",
        "Linienlaser": "Level 1",
        "Lochsäge": "Level 1",
        "Lötgerät": "Level 1",
        "Lötgerät Zubehör": "Level 1",
        "Luftpumpe": "Level 1",
        "Lupe": "Level 1",
        "Mähroboter": "Level 6",
        "Mal Zubehör": "Level 1",
        "Mehrfachstecker + Abzweigstecker": "Level 1",
        "Mehrzweckmesser": "Level 1",
        "Meissel": "Level 1",
        "Messlehre": "Level 1",
        "Messleitung": "Level 1",
        "Messuhr + Messschraube": "Level 1",
        "Metalldetektor": "Level 1",
        "Mikroskop Zubehör": "Level 1",
        "Möbelausstattung": "Level 1",
        "Möbelgleiter + Schutzpuffer": "Level 1",
        "Möbelgriff": "Level 1",
        "Möbelrollen": "Level 1",
        "Möbelscharnier": "Level 1",
        "Motorsteuerung": "Level 1",
        "Multi-Tool": "Level 1",
        "Multifunktionswerkzeug": "Level 1",
        "Multimeter": "Level 1",
        "Muttern + Unterlegscheiben": "Level 1",
        "Nägel": "Level 1",
        "Netzstecker + Netzkupplung": "Level 1",
        "Nieten": "Level 1",
        "Nützlinge": "Level 1",
        "Outdoor Küche": "Level 1",
        "Papierhandtuchspender": "Level 1",
        "Pavillon": "Level 1",
        "Pavillon Zubehör": "Level 1",
        "Pelletgrill": "Level 1",
        "Pellets": "Level 1",
        "Personenschutz": "Level 1",
        "Pestizid": "Level 1",
        "Pfefferspray": "Level 1",
        "Pflanzen": "Level 1",
        "Pflanzen Winterschutz + Gartenvlies": "Level 1",
        "Pflanzen Zubehör": "Level 1",
        "Pflanzenlampe": "Level 1",
        "Pflanzenständer + Blumentreppe": "Level 1",
        "Pinsel": "Level 1",
        "Pipeline": "Level 1",
        "Pizza Zubehör": "Level 1",
        "Pizzaofen": "Level 1",
        "Pool": "Level 1",
        "Pool Ersatzteile": "Level 1",
        "Pool Filter Zubehör": "Level 1",
        "Pool Zubehör": "Level 1",
        "Poolabdeckung": "Level 1",
        "Poolchemie": "Level 1",
        "Poolheizung": "Level 1",
        "Poolreinigung": "Level 1",
        "Poolroboter": "Level 6",
        "Pooltechnik": "Level 1",
        "Power Station": "Level 1",
        "Power Station Zubehör": "Level 1",
        "Presswerkzeug": "Level 1",
        "Profil + Stange": "Level 1",
        "Rasenkante": "Level 1",
        "Rasenmäher": "Level 1",
        "Rasensprenger": "Level 1",
        "Rasentrimmer": "Level 1",
        "Raspel + Feile": "Level 1",
        "Ratsche": "Level 1",
        "Rechen": "Level 1",
        "Regalträger": "Level 1",
        "Regentonne + Erdtanks": "Level 1",
        "Reiseadapter": "Level 1",
        "Relais": "Level 1",
        "Rohrverbindungstechnik": "Level 1",
        "Rostschutz": "Level 1",
        "Rührwerk + Mörtelrührer": "Level 1",
        "Säbelsäge": "Level 1",
        "Sägeblatt": "Level 1",
        "Samen": "Level 1",
        "Sauna": "Level 1",
        "Sauna Zubehör": "Level 1",
        "Schallpegelmessgerät": "Level 1",
        "Schalter + Taster": "Level 1",
        "Scharnier": "Level 1",
        "Schlauchanschluss + Schlauchverbinder": "Level 1",
        "Schleifmaschine + Poliermaschine": "Level 1",
        "Schleifmittel": "Level 1",
        "Schlüsseltresor + Schlüsselschrank": "Level 1",
        "Schneefräse": "Level 1",
        "Schneeschaufel": "Level 1",
        "Schnurschalter": "Level 1",
        "Schrauben": "Level 1",
        "Schraubenschlüssel": "Level 1",
        "Schraubenzieher": "Level 1",
        "Schraubstock + Zwinge": "Level 1",
        "Schrumpfschlauch": "Level 1",
        "Schubkarre": "Level 1",
        "Schubladenauszüge": "Level 1",
        "Schutzanzug + Arbeitsoverall": "Level 1",
        "Schutzbrille + Gesichtsschutz": "Level 1",
        "Schutzhandschuhe": "Level 1",
        "Schutzschalter": "Level 1",
        "Schweissgerät": "Level 1",
        "Schweissgerät Zubehör": "Level 1",
        "Sechskantschlüssel": "Level 1",
        "Seil": "Level 1",
        "Seilzug + Werkstattkran": "Level 1",
        "Sicherheitskennzeichnung": "Level 1",
        "Sicherheitsschuhe": "Level 1",
        "Sicherheitsspiegel": "Level 1",
        "Sicherung": "Level 1",
        "Sichtschutz": "Level 1",
        "Siphon": "Level 1",
        "Smart Plug": "Level 5",
        "Smoker Zubehör": "Level 1",
        "Solaranlage": "Level 1",
        "Solarpanel": "Level 1",
        "Sortimentskasten": "Level 1",
        "Spachtelmasse + Mörtel": "Level 1",
        "Spaten + Schaufel": "Level 1",
        "Spezialfarbe": "Level 1",
        "Spezialsäge": "Level 1",
        "Spiegelschrank": "Level 1",
        "Sprühflasche": "Level 1",
        "Spülbecken": "Level 1",
        "Spülkasten": "Level 1",
        "Stanzwerkzeug": "Level 1",
        "Steckdose": "Level 1",
        "Steckdosenleiste": "Level 1",
        "Steckschlüssel + Stecknuss": "Level 1",
        "Steinkorb": "Level 1",
        "Stichsäge": "Level 1",
        "Strahlregler": "Level 1",
        "Streuwagen + Handstreuer": "Level 1",
        "Stromadapter": "Level 1",
        "Stromgenerator": "Level 1",
        "Stromspeicher": "Level 1",
        "Systemstromversorgung": "Level 1",
        "Tacker + Nagelpistole": "Level 1",
        "Tackerklammern + Tackernägel": "Level 1",
        "Tapete": "Level 1",
        "Taschenlampe": "Level 1",
        "Taschenlampe Zubehör": "Level 1",
        "Taschenmesser": "Level 1",
        "Tierfalle": "Level 1",
        "Tiervertreiber": "Level 1",
        "Tischbohrmaschine": "Level 1",
        "Tischkreissäge": "Level 1",
        "Toilette + Bidet": "Sondertaetigkeit",
        "Transportwagen": "Level 1",
        "Treppengeländer + Handlauf": "Level 1",
        "Tresor": "Level 1",
        "Türband": "Level 1",
        "Türdichtung": "Level 1",
        "Türgriff + Türgarnitur": "Level 1",
        "Türöffner + Türschliesser": "Level 1",
        "Türschloss + Schliesszylinder": "Level 1",
        "Türspion": "Level 1",
        "Überdachung + Carport": "Level 1",
        "Überspannungsschutz": "Level 1",
        "Ventil": "Level 1",
        "Verdünner + Abbeizer": "Level 1",
        "Verkehrstechnik": "Level 1",
        "Verlängerungskabel": "Level 1",
        "Versorgungsbatterie": "Level 1",
        "Verteilerschrank": "Level 1",
        "Verteilerschrank Zubehör": "Level 1",
        "Vertikaler Garten": "Level 1",
        "Vertikutierer": "Level 1",
        "Vorhängeschloss": "Level 1",
        "Wandfarbe": "Level 1",
        "Wärmebildkamera": "Level 4",
        "Warmwassergerät": "Level 1",
        "Warnweste": "Level 1",
        "Waschbecken": "Level 1",
        "Waschtischarmatur": "Level 1",
        "Waschtischkonsole": "Level 1",
        "Wasserpumpe": "Level 1",
        "Wasserwaage": "Level 1",
        "WC Deckel": "Sondertaetigkeit",
        "Weihnachtsbaum": "Level 1",
        "Weihnachtsbaum (echt) + Weihnachtskranz": "Level 1",
        "Werkbank + Arbeitsbock": "Level 1",
        "Werkbank Zubehör": "Level 1",
        "Werkstattschrank": "Level 1",
        "Werkzeugakku + Ladegerät": "Level 1",
        "Werkzeugblock": "Level 1",
        "Werkzeugkoffer": "Level 1",
        "Werkzeugwagen + Montagewagen": "Level 1",
        "Werkzeugwand": "Level 1",
        "Whirlpool": "Level 1",
        "Winkelmesser": "Level 1",
        "Winkelschleifer": "Level 1",
        "Zange": "Level 1",
        "Zange Zubehör": "Level 1",
        "Zaunpfosten + Pfähle": "Level 1",
        "Zeitschaltuhr": "Level 1",
        "Zubehör Antriebstechnik": "Level 1",
        "Zubehör Arbeitsschutz": "Level 1",
        "Zubehör Badmöbel": "Level 1",
        "Zubehör Baustoffe": "Level 1",
        "Zubehör Befestigungstechnik": "Level 1",
        "Zubehör Belüftungstechnik": "Level 1",
        "Zubehör Bewässerung": "Level 1",
        "Zubehör Bohrer": "Level 1",
        "Zubehör Druckluftwerkzeug": "Level 1",
        "Zubehör Elektroinstallation": "Level 1",
        "Zubehör Fensterbeschlag": "Level 1",
        "Zubehör Gartenmaschinen": "Level 1",
        "Zubehör Gartenwerkzeug": "Level 1",
        "Zubehör Gebäudesicherheit": "Level 1",
        "Zubehör Kette + Seil": "Level 1",
        "Zubehör Lagereinrichtung": "Level 1",
        "Zubehör Malerbedarf": "Level 1",
        "Zubehör Maschine": "Level 1",
        "Zubehör Möbelbeschlag": "Level 1",
        "Zubehör Sanitärinstallation": "Level 1",
        "Zubehör Schalterprogramm": "Level 1",
        "Zubehör Schlagwerkzeug": "Level 1",
        "Zubehör Schneidwerkzeug": "Level 1",
        "Zubehör Steuerungstechnik": "Level 1",
        "Zubehör Stromerzeuger": "Level 1",
        "Zubehör Türbeschlag": "Level 1",
        "Zubehör Verlegematerial": "Level 1",
        "Zubehör Werkzeugaufbewahrung": "Level 1",
        "Auto Antenne": "Level 1",
        "Auto Bremsanlage": "Level 1",
        "Auto Camping": "Level 1",
        "Auto Fahrwerk + Auto Antrieb": "Level 1",
        "Auto Innenraum Zubehör": "Level 1",
        "Auto Luftfilter + Ansauganlage": "Level 1",
        "Autobatterie": "Level 1",
        "Autobatterie Ladegerät": "Level 1",
        "Autobatterie Zubehör": "Level 1",
        "Autolampe": "Level 1",
        "Autoradio": "Level 6",
        "Autoradio Installation": "Level 1",
        "Autoradio Zubehör": "Level 1",
        "Autos": "Level 1",
        "Autositzbezüge": "Level 1",
        "Autoteppich": "Level 1",
        "Autotuningteile": "Level 1",
        "Car HiFi Kabel": "Level 1",
        "Car HiFi Lautsprecher": "Level 1",
        "Car HiFi Subwoofer": "Level 1",
        "Car HiFi Verstärker": "Level 1",
        "Dachbox": "Level 1",
        "Dachbox Zubehör": "Level 1",
        "Dachträger": "Level 1",
        "Dachträger Zubehör": "Level 1",
        "Eiskratzer + Scheibenenteiser": "Level 1",
        "Elektroauto Ladekabel": "Level 1",
        "Elektroauto Ladestation": "Level 1",
        "Elektroauto Ladezubehör": "Level 1",
        "Elektroroller": "Level 1",
        "Fahrzeug Werkzeug": "Level 1",
        "Fahrzeugabdeckung": "Level 1",
        "Fahrzeugflüssigkeiten": "Level 1",
        "Fahrzeugreiniger": "Level 1",
        "Fahrzeugreinigung Zubehör": "Level 1",
        "Garagenausstattung": "Level 1",
        "Kennzeichenhalter": "Level 1",
        "Kofferraumwanne": "Level 1",
        "Marderabwehr": "Level 1",
        "Motoröl": "Level 1",
        "Motorrad": "Level 1",
        "Motorrad Regenbekleidung": "Level 1",
        "Motorrad Zubehör": "Level 1",
        "Motorradfunk": "Level 4",
        "Motorradgepäck": "Level 1",
        "Motorradhandschuhe": "Level 1",
        "Motorradhelm": "Sondertaetigkeit",
        "Motorradhelm Zubehör": "Level 1",
        "Motorradhose": "Level 1",
        "Motorradjacke": "Level 1",
        "Motorradkombi": "Level 1",
        "Motorradprotektor": "Level 1",
        "Motorradschuhe": "Level 1",
        "Motorsportbekleidung": "Level 1",
        "Motorsportschuhe": "Level 1",
        "Navigationsgerät": "Level 4",
        "Navigationsgerät Zubehör": "Level 1",
        "On-Board-Diagnose": "kein Demo erstellen!",
        "Pannenhilfe": "Level 1",
        "Radkappen": "Level 1",
        "Reifen": "Level 1",
        "Reifen Zubehör": "Level 1",
        "Rückfahrkamera": "Level 4",
        "Schmiermittel": "Level 1",
        "Schneeketten": "Level 1",
        "Skiträger": "Level 1",
        "Sonnenblende Auto": "Level 1",
        "Spanngurt + Ladungssicherung": "Level 1",
        "Spannungswandler": "Level 1",
        "Starthilfe": "Level 1",
        "Wagenheber": "Level 1",
        "Wassersportträger": "Level 1",
        "Wischerblätter": "Level 1",
        "Zubehör Auto Tuning": "Level 1",
        "Action Cam": "Level 4",
        "Action Cam Zubehör": "Level 1",
        "Akku Ladegerät": "Level 1",
        "Analogfilm": "Level 1",
        "Analogfilmentwicklung": "Level 1",
        "Analogkamera": "Level 4",
        "Batterie Zubehör": "Level 1",
        "Batteriegriff": "Level 1",
        "Batterien + Akkus": "Level 1",
        "Blitzgerät": "Level 1",
        "Blitzgerät Zubehör": "Level 1",
        "Dashcam": "Level 4",
        "Dashcam Zubehör": "Level 1",
        "Dauerlicht": "Level 1",
        "Digitaler Bilderrahmen": "Level 6",
        "Digitalkamera Zubehör": "Level 1",
        "Drohne": "Level 6",
        "Drohne Tasche": "Level 1",
        "Drohne Zubehör": "Level 1",
        "Einwegkamera": "Level 1",
        "Fernauslöser": "Level 1",
        "Gegenlichtblende": "Level 1",
        "Gimbal": "Level 1",
        "Gimbal Zubehör": "Level 1",
        "Hintergrundsystem": "Level 1",
        "Kamera": "Level 4",
        "Kamera Stromversorgung": "Level 1",
        "Kameragurt": "Level 1",
        "Kamerareinigung": "Level 1",
        "Kameraschutz": "Level 1",
        "Kamerasucher": "Level 1",
        "Kameratasche": "Level 1",
        "Lampenstativ": "Level 1",
        "Objektiv": "Level 1",
        "Objektivadapter": "Level 1",
        "Objektivdeckel": "Level 1",
        "Objektivfilter": "Level 1",
        "Objektivfilter Zubehör": "Level 1",
        "Objektivkonverter": "Level 1",
        "Sofortbildfilm": "Level 1",
        "Sofortbildkamera": "Level 1",
        "Softbox + Reflektor": "Level 1",
        "Softbox + Reflektor Zubehör": "Level 1",
        "Speicherkarte": "Sondertaetigkeit",
        "Speicherkartenlesegerät": "Level 1",
        "Stativ": "Level 1",
        "Stativ Zubehör": "Level 1",
        "Stativkopf": "Level 1",
        "Studioausrüstung Zubehör": "Level 1",
        "Studioblitz": "Level 1",
        "Studioblitz Zubehör": "Level 1",
        "Studiokoffer + Studiotasche": "Level 1",
        "Video Monitor": "Level 2",
        "Video Zubehör": "Level 1",
        "Videokamera": "Level 4",
        "Abfalleimer": "Level 1",
        "Abfallsack": "Level 1",
        "Abtropfgestell": "Level 1",
        "Aschenbecher": "Level 1",
        "Auflaufform": "Level 1",
        "Ausstechformen": "Level 1",
        "Backblech": "Level 1",
        "Backform": "Level 1",
        "Backhandschuhe + Topflappen": "Level 1",
        "Backpapier": "Level 1",
        "Backutensilien": "Level 1",
        "Bar Zubehör": "Level 1",
        "Besteck": "Level 1",
        "Besteckkasten": "Level 1",
        "Biergläser": "Level 1",
        "Brotaufbewahrung": "Level 1",
        "Buffet Präsentation": "Level 1",
        "Cake Design Utensilien": "Level 1",
        "Caquelon": "Level 1",
        "Cocktailgläser": "Level 1",
        "Dosenöffner": "Level 1",
        "Eierbecher": "Level 1",
        "Einmachgläser": "Level 1",
        "Einwegbehälter": "Level 1",
        "Einweggeschirr": "Level 1",
        "Eisformen": "Level 1",
        "Eisherstellung": "Level 1",
        "Entkalker": "Level 1",
        "Entsteiner": "Level 1",
        "Essstäbchen": "Level 1",
        "Flachmann": "Level 1",
        "Flaschenkühler": "Level 1",
        "Flaschenöffner": "Level 1",
        "Fondue Set": "Level 1",
        "Fusselentferner": "Level 1",
        "Gastro Kücheneinrichtung": "Level 1",
        "Gastronormbehälter": "Level 1",
        "Gastrowagen": "Level 1",
        "Geschirrset": "Level 1",
        "Geschirrspülmittel": "Level 1",
        "Haushaltspapier": "Level 1",
        "Humidor": "Level 1",
        "Knoblauchpresse": "Level 1",
        "Kochbesteck": "Level 1",
        "Küchen Organizer": "Level 1",
        "Küchengadgets": "Level 1",
        "Küchenmesser": "Level 1",
        "Küchenreibe": "Level 1",
        "Küchenrollenhalter": "Level 1",
        "Küchensieb": "Level 1",
        "Kuchentransportbox": "Level 1",
        "Küchenwaage": "Level 1",
        "Küchenwecker": "Level 1",
        "Lebensmittelverpackung": "Level 1",
        "Lufterfrischer": "Level 1",
        "Lunchbox": "Level 1",
        "Menage": "Level 1",
        "Messbecher": "Level 1",
        "Messerblock": "Level 1",
        "Messerschärfer": "Level 1",
        "Milchkanne": "Level 1",
        "Mörser": "Level 1",
        "Ölspender + Essigspender": "Level 1",
        "Pfanne + Kochtopf": "Level 1",
        "Pfeffermühle + Salzmühle": "Level 1",
        "Rahmbläser": "Level 1",
        "Rechaud": "Level 1",
        "Reinigung PC + Peripherie": "Level 1",
        "Reinigungsmittel": "Level 1",
        "Reinigungsutensil": "Level 1",
        "Saucenspender": "Level 1",
        "Schneidebrett": "Level 1",
        "Schuhlöffel": "Level 1",
        "Schuhpflege": "Level 1",
        "Schuhspanner": "Level 1",
        "Schüssel + Schale": "Level 1",
        "Schwingbesen": "Level 1",
        "Servierbesteck": "Level 1",
        "Serviergefässe": "Level 1",
        "Serviergeschirr": "Level 1",
        "Serviettenhalter": "Level 1",
        "Serviettenringe": "Level 1",
        "Sohlen": "Level 1",
        "Sparschäler": "Level 1",
        "Spritzbeutel": "Level 1",
        "Strohhalm": "Sondertaetigkeit",
        "Tablett": "Sondertaetigkeit",
        "Tasse": "Level 1",
        "Teekanne": "Level 1",
        "Teller": "Level 1",
        "Thermoskanne": "Level 1",
        "Toilettenpapier": "Level 1",
        "Trinkgläser": "Level 1",
        "Untersetzer": "Level 1",
        "Vape Zubehör": "Sondertaetigkeit",
        "Vorratsbehälter": "Level 1",
        "Wallholz": "Level 1",
        "Wäscheständer": "Level 1",
        "Waschmittel + Textilpflege": "Sondertaetigkeit",
        "Wasserfilter": "Sondertaetigkeit",
        "Wasserfilterkanne": "Level 1",
        "Wein Zubehör": "Level 1",
        "Weingläser": "Level 1",
        "Zubehör Buffet + Anrichten": "Level 1",
        "Zubehör Gastroküche": "Level 1",
        "Zubehör Gedeckter Tisch": "Level 1",
        "Zubehör Kochen am Tisch": "Level 1",
        "Zubehör Kochgeschirr": "Sondertaetigkeit",
        "3D Drucker": "Level 4",
        "3D Drucker Zubehör": "Level 1",
        "3D Filament": "Level 1",
        "3D Scanner": "Level 4",
        "Access Point": "Level 4",
        "Aktenvernichter": "Level 1",
        "Aktenvernichter Zubehör": "Level 1",
        "Aktive Bauelemente": "Level 1",
        "AR Brille": "Level 6",
        "Automatisierung": "Level 1",
        "Barcode Scanner": "Level 1",
        "Barcode Scanner Zubehör": "Level 1",
        "Barebone": "Sondertaetigkeit",
        "Belegdrucker": "Level 1",
        "Beschriftungsgerät": "Level 1",
        "Beschriftungsgerät Zubehör": "Level 1",
        "Bindegerät": "Level 1",
        "Bindegerät Zubehör": "Level 1",
        "Cartridge": "Level 1",
        "Computer Werkzeug": "Level 1",
        "CPU Kühler": "Level 1",
        "CPU Wasserkühler": "Level 1",
        "CPU Wasserkühler Zubehör": "Level 1",
        "Crypto Wallet": "keine Demos",
        "Data + Video Adapter": "Level 1",
        "Data Converter": "Level 1",
        "Digital Signage": "Sondertaetigkeit",
        "Digital Signage Zubehör": "Level 1",
        "Diode": "Level 1",
        "Dockingstation + USB Hub": "Level 1",
        "Dockingstation Refurbished": "Level 1",
        "Drucker": "Level 4",
        "Drucker Zubehör": "Level 1",
        "Druckerserver": "Level 1",
        "Elektronikkabel + Stecker": "Level 1",
        "Elektronikmodul": "Level 1",
        "Elektronikzubehör + Gehäuse": "Level 1",
        "Entwicklungsboard + Kit": "Level 1",
        "Entwicklungsboard Zubehör": "Level 1",
        "Etikettendrucker": "Level 1",
        "Etikettenrolle": "Level 1",
        "Externe Festplatte": "Sondertaetigkeit",
        "Externe SSD": "Sondertaetigkeit",
        "Falzmaschine": "Level 1",
        "Fax": "Level 4",
        "Fax Zubehör": "Level 1",
        "Feinwaage": "Level 1",
        "Festplatte": "Sondertaetigkeit",
        "Festplattengehäuse": "Level 1",
        "Firewall": "Level 4",
        "Game": "Level 1",
        "Game (Download)": "Demo nicht möglich",
        "Game Recorder": "Level 1",
        "Gaming Controller": "Level 1",
        "Gaming Controller Zubehör": "Level 1",
        "Gaming Headset": "Level 1",
        "Gaming Stuhl": "Level 1",
        "Gaming Tisch": "Level 1",
        "Garantieerweiterung": "Demo nicht möglich",
        "Garantieerweiterung (Download)": "Demo nicht möglich",
        "Geldzähler": "Level 1",
        "GPU Wasserkühler": "Level 1",
        "GPU Wasserkühler Zubehör": "Level 1",
        "Grafikkarte": "Level 1",
        "Grafiktablett": "Sondertaetigkeit",
        "Gravierer": "Sondertaetigkeit",
        "Headset Zubehör": "Level 1",
        "Induktor": "Level 1",
        "Ingame Währung": "Level 1",
        "Interne Kabel (PC)": "Level 1",
        "Kasse": "Level 6",
        "Kasse Zubehör": "Level 1",
        "Kassensystem": "Level 6",
        "Keycaps": "Level 1",
        "Kondensator": "Level 1",
        "Konferenzgerät": "Level 6",
        "Konferenzgerät Zubehör": "Level 1",
        "Kontrollerkarte": "Level 1",
        "KVM Switch": "Level 1",
        "KVM-Switch Kabel": "Level 1",
        "Labornetzgerät": "Level 1",
        "Laminierfolie": "Level 1",
        "Laminiergerät": "Level 1",
        "Laserpointer": "Level 1",
        "Lizenz": "Level 1",
        "Lüftersteuerung": "Level 1",
        "Mainboard": "Level 6",
        "Mainboard Wasserkühler": "Level 1",
        "Mainboard Zubehör": "Level 1",
        "Maus": "Level 1",
        "Maus + Tastatur Zubehör": "Level 1",
        "Mausmatte": "Level 1",
        "Messtechnik": "Level 1",
        "Modding Beleuchtung": "Level 1",
        "Monitor": "Level 2",
        "Monitor Erhöhung": "Level 1",
        "Monitor Halterung": "Level 1",
        "Monitor Refurbished": "Level 2",
        "Monitor Schutzfolie": "Level 1",
        "Monitor Zubehör": "Level 1",
        "NAS": "Sondertaetigkeit",
        "NAS Zubehör": "Level 1",
        "Netzwerk Switch": "Level 1",
        "Netzwerkadapter": "Level 1",
        "Netzwerkantenne": "Level 1",
        "Netzwerkkabel": "Level 1",
        "Netzwerkkamera": "Level 5",
        "Netzwerkkamera Zubehör": "Level 1",
        "Netzwerkkarte": "Level 1",
        "Notebook": "Sondertaetigkeit",
        "Notebook Akku": "Level 1",
        "Notebook Ersatzteile": "Level 1",
        "Notebook Netzteil": "Level 1",
        "Notebook Refurbished": "Sondertaetigkeit",
        "Notebook Schutzfolie": "Level 1",
        "Notebook Security": "Level 1",
        "Notebook Ständer": "Level 1",
        "Notebooktasche": "Level 1",
        "Notebookwagen": "Level 1",
        "Office Headset": "Level 1",
        "Optisches Laufwerk": "Level 1",
        "Oszillator": "Level 1",
        "Passive Bauelemente": "Level 1",
        "PC": "Sondertaetigkeit",
        "PC Gehäuse": "Level 6",
        "PC Gehäuse Zubehör": "Level 1",
        "PC Lautsprecher": "Level 1",
        "PC Lüfter": "Level 1",
        "PC Lüfter Zubehör": "Level 1",
        "PC Netzteil": "Level 1",
        "PC Refurbished": "Sondertaetigkeit",
        "PC Zubehör": "Level 1",
        "PoE Injector": "Level 1",
        "Powerline": "Level 1",
        "Presenter": "Level 1",
        "Prozessor": "Level 1",
        "RAM": "Level 1",
        "RAM Modellspezifisch": "Level 1",
        "Retro Gaming": "Level 1",
        "Robotik Kit": "Level 1",
        "Robotik Modul": "Level 1",
        "Robotik Zubehör": "Level 1",
        "Router": "Level 3 (Fritzboxen Level 4)",
        "Scanner": "Level 1",
        "Scanner Zubehör": "Level 1",
        "Schneidemaschine": "Level 1",
        "Schreibmaschine Zubehör": "Level 1",
        "Screenbar": "Level 1",
        "Server": "Level 1",
        "Server Barebone": "Level 6",
        "Server Zubehör": "Level 1",
        "Serverschrank": "Level 1",
        "Serverschrank Zubehör": "Level 1",
        "Sim Rig": "Level 1",
        "Smart Home Hub": "Level 5",
        "Software": "Level 1",
        "Software Box": "Level 1",
        "Soundkarte": "Level 1",
        "Speicher Wasserkühler": "Level 1",
        "Spezial Büromaschinen": "Level 1",
        "Spielkonsole": "Level 5",
        "SSD": "Sondertaetigkeit",
        "SSD + Festplatte Zubehör": "Level 1",
        "Storage Controller": "Level 1",
        "Storagesystem": "Level 1",
        "Streaming Deck": "Level 1",
        "Switch Box": "Level 1",
        "Taschenrechner": "Level 1",
        "Taschenrechner Zubehör": "Level 1",
        "Tastatur": "Level 1",
        "Telefon": "Level 4",
        "Telefon Zubehör": "Level 1",
        "Transceiver": "Level 1",
        "Transformator": "Level 1",
        "Transistor": "Level 1",
        "TV-Karte": "Level 1",
        "USB Stick": "Sondertaetigkeit",
        "USV": "Level 1",
        "USV Zubehör": "Level 1",
        "VR Brille": "Level 4",
        "Wärmeleitpad": "Level 1",
        "Wärmeleitpaste": "Level 1",
        "Wasserkühlung Anschluss": "Level 1",
        "Wasserkühlung Ausgleichsbehälter": "Level 1",
        "Wasserkühlung Komponenten Zubehör": "Level 1",
        "Wasserkühlung Pumpe": "Level 1",
        "Wasserkühlung Radiator": "Level 1",
        "Wasserkühlung Schlauch": "Level 1",
        "Wasserkühlung Überwachung": "Level 1",
        "Wasserkühlung Wasserzusatz": "Level 1",
        "Webcam": "Level 1",
        "Weiteres Gaming Zubehör": "Level 1",
        "Widerstand": "Level 1",
        "WLAN Repeater": "Level 4",
        "Zeiterfassungssystem": "Level 1",
        "Zubehör Gaming Möbel": "Level 1",
        "Zubehör Netzwerk": "Level 1",
        "Zubehör VR + AR": "Level 1",
        "Digitale Guthabenkarte": "Level 1",
        "Erotikfilm": "Level 1",
        "Fachbücher": "Level 1",
        "Hörbücher": "Level 1",
        "Internet Abo": "Level 1",
        "Jazz": "Level 1",
        "Kinderbücher": "Level 1",
        "Klassik": "Level 1",
        "Landkarte": "Level 1",
        "Mobile-Abo + SIM-Karte": "Level 1",
        "Pop": "Level 1",
        "Ratgeber": "Level 1",
        "Sachbücher": "Level 1",
        "Schallplatten": "Level 1",
        "Schulbücher": "Level 1",
        "Sonstige CDs": "Level 1",
        "Sonstige Literatur": "Level 1",
        "Spielfilme + Serien": "Level 1",
        "TV Abo": "Level 1",
        "Zeitschriften Abo": "Level 1",
        "Auto Adapter": "Level 1",
        "eReader": "Level 6",
        "eReader Hülle": "Level 1",
        "Geräte Schutzfolie": "Level 1",
        "Handykette": "Level 1",
        "Mobilgerät Adapter": "Level 1",
        "Mobilgerät Ersatzteile": "Level 1",
        "Powerbank": "Level 1",
        "Pulsgurt": "Level 1",
        "Selfie Stick": "Level 1",
        "Smart Ring": "Level 6",
        "Smart Ring Zubehör": "Level 1",
        "Smartphone": "Sondertaetigkeit",
        "Smartphone Akku": "Level 1",
        "Smartphone Halterung": "Level 1",
        "Smartphone Hülle": "Level 1",
        "Smartphone Refurbished": "Sondertaetigkeit",
        "Smartphone Schutzfolie": "Level 1",
        "Smartphone Sportarmband": "Level 1",
       "Smartwatch": "Sondertaetigkeit: Apple / Xiaomi / Huawei / Google / Samsung / OnePlus / restlichen Level 6",
        "Smartwatch Refurbished": "Sondertaetigkeit: Apple / Xiaomi / Huawei / Google / Samsung / OnePlus / restlichen Level 6",
        "Smartwatch Schutzfolie": "Level 1",
        "Smartwatch Zubehör": "Level 1",
        "Stylus": "Level 1",
        "Stylus Zubehör": "Level 1",
        "Tablet": "Sondertaetigkeit",
        "Tablet Halterung": "Level 1",
        "Tablet Hülle": "Level 1",
        "Tablet Refurbished": "Sondertaetigkeit",
        "Tablet Schutzfolie": "Level 1",
        "Tablet Tastatur": "Level 1",
        "Tastenhandy": "Sondertaetigkeit",
        "Tracker": "Level 5",
        "Tracker Zubehör": "Level 1",
        "Uhrenarmband": "Level 1",
        "USB Ladegerät": "Level 1",
        "Walkie Talkie": "Level 1",
        "Walkie Talkie Zubehör": "Level 1",
        "Weiteres Smartphone Zubehör": "Level 1",
        "Wireless Charger": "Level 1",
        "Akupressurmatte": "Level 1",
        "Alkoholtester": "Sondertaetigkeit",
        "Aufschnittmaschine": "Level 1",
        "Backofen + Herd Einbau": "Level 1",
        "Backofen + Herd Freistehend": "Level 1",
        "Backofen Einbau": "Level 1",
        "Blutdruckmessgerät": "Sondertaetigkeit",
        "Bluttest": "Sondertaetigkeit",
        "Brotbackautomat": "Level 1",
        "Bügelbrett": "Level 1",
        "Bügeleisen": "Level 1",
        "Dampfgarer + Reiskocher": "Level 1",
        "Dampfglätter": "Level 1",
        "Dampfreiniger": "Level 1",
        "Dampfreiniger Zubehör": "Level 1",
        "Dörrautomat": "Level 1",
        "Dunstabzugshaube": "Level 1",
        "Eierkocher": "Level 1",
        "Einbaukühlschrank": "Level 1",
        "Einkochautomat": "Level 1",
        "Elektrische Zahnbürste": "Sondertaetigkeit",
        "EMS + TENS Gerät": "Sondertaetigkeit",
        "Entsafter": "Level 1",
        "Epilierer": "Sondertaetigkeit",
        "Espressokocher": "Level 1",
        "Faszienball + Faszienrolle": "Level 1",
        "Fensterputzroboter": "Level 6",
        "Fensterputzroboter Zubehör": "Level 1",
        "Fenstersauger": "Level 1",
        "Fenstersauger Zubehör": "Level 1",
        "Fieberthermometer": "Level 1",
        "Filterkaffeemaschine": "Sondertaetigkeit",
        "Fleischwolf": "Level 1",
        "Föhn": "Level 1",
        "Föhn Zubehör": "Level 1",
        "Food Center": "Level 1",
        "Fritteuse": "Level 1",
        "Fun Kitchen": "Level 1",
        "Fusspflegegerät": "Sondertaetigkeit",
        "Fusspflegegerät Zubehör": "Sondertaetigkeit",
        "Garn + Wolle": "Level 1",
        "Gastro Küchengeräte": "Level 1",
        "Gefrierschrank + Gefriertruhe": "Level 1",
        "Geschirrspüler Einbau": "Level 1",
        "Geschirrspüler Freistehend": "Level 1",
        "Geschirrspüler Zubehör": "Level 1",
        "Gesichtspflegegerät": "Sondertaetigkeit",
        "Gesichtspflegegerät Zubehör": "Level 1",
        "Getränkespender": "Level 1",
        "Getränkespender Zubehör": "Level 1",
        "Glätteisen": "Level 1",
        "Handarbeitsset": "Level 1",
        "Handmixer": "Level 1",
        "Handwärmer + Fusswärmer": "Level 1",
        "Heizdecke": "Level 1",
        "Heizkissen": "Level 1",
        "Heizkörper": "Level 1",
        "Heizlüfter": "Level 1",
        "Heizstrahler": "Level 1",
        "Hörgerät": "Sondertaetigkeit",
        "Infrarotlampe": "Level 1",
        "Inhalator": "Sondertaetigkeit",
        "IPL Gerät": "Sondertaetigkeit",
        "Kaffeebereiter": "Level 1",
        "Kaffeemühle": "Level 1",
        "Kaffeevollautomat": "Sondertaetigkeit",
        "Kaffeevollautomat Einbau": "Sondertaetigkeit",
        "Kapselmaschine": "Sondertaetigkeit",
        "Kleinbackofen": "Level 1",
        "Klimaanlage": "Level 1",
        "Klimaanlage Zubehör": "Level 1",
        "Kochfeld": "Level 1",
        "Kochplatte": "Level 1",
        "Komplettküche": "Level 1",
        "Kontaktgrill": "Level 1",
        "Küchenmaschine": "Level 1",
        "Kühlschrank Freistehend": "Level 1",
        "Kühlschrank Zubehör": "Level 1",
        "Lockenstab": "Level 1",
        "Luftbefeuchter": "Level 1",
        "Luftentfeuchter": "Level 1",
        "Luftreiniger": "Level 1",
        "Massagegerät": "Level 1",
        "Massageliege + Massagesessel": "Level 1",
        "Massagepistole": "Level 1",
        "Massagezubehör": "Sondertaetigkeit",
        "Mikrowelle": "Level 1",
        "Mikrowelle Einbau": "Level 1",
        "Milchaufschäumer": "Level 1",
        "Munddusche": "Sondertaetigkeit",
        "Nagelpflegegerät": "Sondertaetigkeit",
        "Nagelpflegegerät Zubehör": "Sondertaetigkeit",
        "Nähmaschine": "Level 1",
        "Nähzubehör": "Level 1",
        "Nassreiniger": "Level 1",
        "Nassreiniger Zubehör": "Level 1",
        "Pastamaschine": "Level 1",
        "Personenwaage": "Level 1",
        "Polsterreiniger + Teppichreiniger": "Level 2",
        "Pulsoximeter + EKG": "Level 1",
        "Racletteofen": "Level 1",
        "Rasierapparat": "Sondertaetigkeit",
        "Raumluftwäschetrockner": "Level 1",
        "Recovery Manschetten": "Sondertaetigkeit",
        "Reissverschluss": "Level 1",
        "Schlaftherapie": "Level 1",
        "Schnittmuster": "Level 1",
        "Siebträgermaschine": "Sondertaetigkeit",
        "Speisewärmer": "Level 1",
        "Stabmixer": "Level 1",
        "Standmixer": "Level 1",
        "Staubsauger": "Level 1",
        "Staubsauger Roboter": "Level 5",
        "Staubsauger Roboter Zubehör": "Level 1",
        "Staubsauger Zubehör": "Level 1",
        "Staubsaugerbeutel": "Level 1",
        "Steamer Einbau": "Level 1",
        "Stoff": "Level 1",
        "Tageslichtlampe": "Level 1",
        "Tee Zubehör": "Level 1",
        "Thermometer + Hygrometer": "Level 1",
        "Thermostat": "Level 1",
        "Tischgrill": "Level 1",
        "Toaster": "Level 1",
        "Trimmer + Haarschneider": "Sondertaetigkeit",
        "Ultraschallreiniger": "Level 1",
        "Vakuumiergerät": "Level 1",
        "Ventilator": "Level 1",
        "Waffeleisen": "Level 1",
        "Wärmeschublade": "Level 1",
        "Warmluftbürste": "Level 1",
        "Wäschetrockner": "Level 1",
        "Waschmaschine": "Level 1",
        "Waschtrockner": "Level 1",
        "Waschturm": "Level 1",
        "Wasserkocher": "Level 1",
        "Wassersprudler": "Level 1",
        "Wassersprudler Zubehör": "Level 1",
        "Weinkühlschrank Einbau": "Level 1",
        "Weinkühlschrank Freistehend": "Level 1",
        "Wetterstation": "Level 1",
        "Wetterstation Zubehör": "Level 1",
        "Zahnbürstenkopf": "Sondertaetigkeit",
        "Zerkleinerer": "Level 1",
        "Zubehör Bügeln + Wäschepflege": "Level 1",
        "Zubehör Gesundheitsmessgeräte": "Level 1",
        "Zubehör Haarentfernung": "Sondertaetigkeit",
        "Zubehör Heizen": "Level 1",
        "Zubehör Kaffeemaschinen": "Level 1",
        "Zubehör Kochen + Backen": "Level 1",
        "Zubehör Küchengeräte": "Level 1",
        "Zubehör Luftbehandlung": "Level 1",
        "Zubehör Mixen + Schneiden": "Level 1",
        "Zubehör Waschen + Trocknen": "Level 1",
        "Zubehör Zahnpflege": "Sondertaetigkeit",
        "Zyklustracker": "Sondertaetigkeit",
        "Adventskalender": "Level 1",
        "Airbrush": "Level 1",
        "Autorennbahn": "Level 1",
        "Autorennbahn Zubehör": "Level 1",
        "Babybücher": "Level 1",
        "Babyrassel": "Level 1",
        "Badespielzeug": "Level 1",
        "Bällebad": "Level 1",
        "Bastelfilz": "Level 1",
        "Bastelperlen": "Level 1",
        "Bastelset": "Level 1",
        "Baukasten": "Level 1",
        "Bausatz": "Level 1",
        "Bausteine": "Level 1",
        "Berufsrollenspiele": "Level 1",
        "Bewegungsspielzeug": "Level 1",
        "Billard Zubehör": "Level 1",
        "Billardtisch": "Level 1",
        "Blaster": "Level 1",
        "Brettspiele": "Level 1",
        "Bügelperlen": "Level 1",
        "Dart Flight": "Level 1",
        "Dart Shaft": "Level 1",
        "Dartpfeile": "Level 1",
        "Dartscheibe": "Level 1",
        "Dartspitzen": "Level 1",
        "Diabolo": "Level 1",
        "Drachen": "Level 1",
        "Dreirad": "Level 1",
        "Experimentierkasten": "Level 1 (Originalverpackung)",
        "Ferngesteuertes für Kinder": "Level 1",
        "Feuerwerk": "Sondertaetigkeit",
        "Frisierkopf": "Level 1",
        "Geschicklichkeitsspiele": "Level 1",
        "Glücksspiele": "Level 1",
        "Go-Kart": "Level 1",
        "Greifling": "Level 1",
        "Grundmaterial Basteln": "Level 1",
        "Holzeisenbahn": "Level 1",
        "Hörspiel": "Level 1",
        "Hüpftier": "Level 1",
        "Jonglieren": "Level 1",
        "Kartenspiele": "Level 1",
        "Kaufladen": "Level 1",
        "Kaufladen Zubehör": "Level 1",
        "Kinder Elektroauto": "Level 1",
        "Kinder Elektroauto Zubehör": "Level 1",
        "Kinderball": "Level 1",
        "Kindergartenbank": "Level 1",
        "Kinderkamera": "Level 4",
        "Kinderkopfhörer": "Level 1",
        "Kinderküche": "Level 1",
        "Kinderküche Zubehör": "Level 1",
        "Kindermikroskop": "Level 1 (Originalverpackung)",
        "Kinderradio": "Level 1",
        "Kindertraktor": "Level 1",
        "Kindertraktor Zubehör": "Level 1",
        "Kinderwerkbank": "Level 1",
        "Klemmbausteine": "Level 1",
        "Klemmbausteine Zubehör": "Level 1",
        "Knete": "Level 1",
        "Knobelspiele": "Level 1",
        "Kostüm": "Level 1",
        "Kostüm Accessoire": "Level 1",
        "Krabbeldecke + Spielbogen": "Level 1",
        "Kugelbahn": "Level 1",
        "Lauflernhilfe": "Level 1",
        "Legespiele": "Level 1",
        "LEGO": "Level 1",
        "LEGO DUPLO": "Level 1",
        "Leiterwagen": "Level 1",
        "Lernspiel": "Level 1",
        "Luftballon": "Level 1",
        "Luftballon Zubehör": "Level 1",
        "Luftmatratze": "Level 1",
        "Malset": "Level 1",
        "Maltafel": "Level 1",
        "Mikroskop": "Level 1 (Originalverpackung)",
        "Modellauto": "Level 1",
        "Modellbaufarbe": "Level 1",
        "Modelleisenbahn Anlagenbau": "Level 1",
        "Modelleisenbahn Elektronik": "Level 1",
        "Modelleisenbahn Gleis": "Level 1",
        "Modelleisenbahn Lokomotive": "Level 1",
        "Modelleisenbahn Wagen": "Level 1",
        "Modelliermasse": "Level 1",
        "Moosgummi": "Level 1",
        "Motorikspielzeug": "Level 1",
        "Musikspielzeug": "Level 1",
        "Partydekoration": "Level 1",
        "Partyspiele": "Level 1",
        "Planschbecken": "Level 1",
        "Playmobil": "Level 1",
        "Plüschtier": "Level 1",
        "Puppe": "Level 1",
        "Puppenhaus": "Level 1",
        "Puppentheater": "Level 1",
        "Puppenwagen": "Level 1",
        "Puzzle": "Level 1",
        "Rätselspiele": "Level 1",
        "RC Akku": "Level 1",
        "RC Auto": "Level 1",
        "RC Auto Zubehör": "Level 1",
        "RC Boot": "Level 1",
        "RC Boot Zubehör": "Level 1",
        "RC Empfänger": "Level 1",
        "RC Flugzeug": "Level 1",
        "RC Flugzeug Zubehör": "Level 1",
        "RC Helikopter": "Level 1",
        "RC Helikopter Zubehör": "Level 1",
        "RC Kabel + RC Stecker": "Level 1",
        "RC Ladegerät": "Level 1",
        "RC Lipo Bag": "Level 1",
        "RC Motor": "Level 1",
        "RC Servo": "Level 1",
        "Rutschauto": "Level 1",
        "Rutschauto Zubehör": "Level 1",
        "Rutschbahn": "Level 1",
        "Sammelfigur": "Level 1",
        "Sammelkarten": "Level 1",
        "Sammelkarten Zubehör": "Level 1",
        "Sandkasten": "Level 1",
        "Sandkasten Spielzeug": "Level 1",
        "Schach": "Level 1",
        "Schaukel": "Level 1",
        "Schaukelpferd + Reittier": "Level 1",
        "Scherzartikel": "Level 1",
        "Schiebespielzeug": "Level 1",
        "Schlagspiel": "Level 1",
        "Schminke": "Sondertaetigkeit",
        "Schmusetuch": "Level 1",
        "Schneideplotter + Transferpresse": "Level 1",
        "Schneideplotter Zubehör": "Level 1",
        "Seifenblasen": "Level 1",
        "Slackline": "Level 1",
        "Soft Play": "Level 1",
        "Sonstige Spiele": "Level 1",
        "Sortierspielzeug": "Level 1",
        "Spielesammlung": "Level 1",
        "Spielgarage": "Level 1",
        "Spielhaus": "Level 1",
        "Spielteppich + Spielmatte": "Level 1",
        "Spieltisch Zubehör": "Level 1",
        "Spielturm": "Level 1",
        "Spieluhr": "Level 1",
        "Spielzelt": "Level 1",
        "Spielzeugauto": "Level 1",
        "Spielzeugauto Zubehör": "Level 1",
        "Spielzeugfigur": "Level 1",
        "Strassenkreide": "Level 1",
        "Tabletop Miniaturen": "Level 1",
        "Temporäre Tattoos": "Level 1",
        "Tischfussball + Spieltisch": "Level 1",
        "Trampolin": "Level 1",
        "Trampolin Zubehör": "Level 1",
        "Washi Tape": "Level 1",
        "Wasserbahn": "Level 1",
        "Wasserball": "Level 1",
        "Wasserballon": "Level 1",
        "Wasserpistole": "Level 1",
        "Wasserrutsche": "Level 1",
        "Würfel": "Level 1",
        "Würfelspiele": "Level 1",
        "Wurfspiel": "Level 1",
        "Zauberkasten": "Level 1 (Originalverpackung)",
        "Zauberwürfel": "Level 1",
        "Zubehör Basteln": "Level 1",
        "Zubehör Dart": "Level 1",
        "Zubehör Gartenspielgeräte": "Level 1",
        "Zubehör Gesellschaftsspiel": "Level 1",
        "Zubehör Modellbau": "Level 1",
        "Zubehör Puppen": "Level 1",
        "Zubehör RC Elektronik": "Level 1",
        "American Footballs": "Level 1",
        "Angelhaken": "Level 1",
        "Angelköder": "Level 1",
        "Angelrolle": "Level 1",
        "Angelrute": "Level 1",
        "Angelschnur": "Level 1",
        "Angelzubehör": "Level 1",
        "Atemregler": "Sondertaetigkeit",
        "Badekappe": "Level 1",
        "Badmintonschläger": "Level 1",
        "Balance Trainer": "Level 1",
        "Baseballhandschuh": "Level 1",
        "Baseballs": "Level 1",
        "Baseballschläger": "Level 1",
        "Basketbälle": "Level 1",
        "Basketballkorb": "Level 1",
        "Bauchtrainer": "Level 1",
        "BMX": "Level 1",
        "Bob + Schlitten": "Level 1",
        "Boule Spiel": "Level 1",
        "Boxhandschuhe": "Level 1",
        "Boxsack": "Level 1",
        "Boxsack Zubehör": "Level 1",
        "Bremsbeläge": "Level 1",
        "Bremsscheibe": "Level 1",
        "Brillenersatzgläser": "Level 1",
        "Campingbesteck": "Level 1",
        "Campinggeschirr": "Level 1",
        "Campingkocher": "Level 1",
        "Campinglampe": "Level 1",
        "Campingmöbel": "Level 1",
        "Campingstuhl": "Level 1",
        "Campingtisch": "Level 1",
        "Chalk": "Level 1",
        "Citybike": "Level 1",
        "Crosstrainer": "Level 1",
        "E-Bike": "Level 1",
        "E-Bike Akku + E-Bike Ladegerät": "Level 1",
        "E-Bike Zubehör": "Level 1",
        "E-Scooter": "Level 5",
        "Echolot": "Level 1",
        "Einrad": "Level 1",
        "Eishockeyhelm": "Sondertaetigkeit",
        "Eishockeyprotektoren": "Level 1",
        "Eishockeystock": "Level 1",
        "Eispickel": "Level 1",
        "Elektroskateboard": "Level 6",
        "Erlebnisgutschein": "Level 1",
        "Federbälle": "Level 1",
        "Felgenband": "Level 1",
        "Felgenbremse": "Level 1",
        "Fernglas": "Level 1",
        "Fitnessband": "Level 1",
        "Fitnessboden": "Level 1",
        "Fitnesstrampolin": "Level 1",
        "Flaschenhalter": "Level 1",
        "Fliegenmaske": "Sondertaetigkeit",
        "Flossen": "Level 1",
        "Funtube": "Level 1",
        "Fussbälle": "Level 1",
        "Gaskartusche": "Level 1",
        "Gepäckträger": "Level 1",
        "Golf Trolley": "Level 1",
        "Golfbag": "Level 1",
        "Golfball": "Level 1",
        "Golfschläger": "Level 1",
        "GPS Gerät": "Level 4",
        "Gravel Bike": "Level 1",
        "Gymnastikball": "Level 1",
        "Halfter": "Level 1",
        "Handbälle": "Level 1",
        "Handtrainer": "Level 1",
        "Hantelbank": "Level 1",
        "Hanteln": "Level 1",
        "Hantelscheiben": "Level 1",
        "Hantelständer": "Level 1",
        "Hantelstange": "Level 1",
        "Hometrainer": "Level 1",
        "Hoverboard": "Level 1",
        "Hula Hoop Reifen": "Level 1",
        "Inline Skates": "Level 1",
        "Inline Skates Zubehör": "Level 1",
        "Isomatte": "Level 1",
        "Jagdzubehör": "Level 1",
        "Kajak": "Level 1",
        "Kampfsport Schutzausrüstung": "Level 1",
        "Kampfsportbekleidung": "Level 1",
        "Kampfsportschuhe": "Level 1",
        "Karabiner": "Level 1",
        "Kettenblatt": "Level 1",
        "Kettlebell": "Level 1",
        "Kindervelo": "Level 1",
        "Kite": "Level 1",
        "Kite Zubehör": "Level 1",
        "Kiteboard": "Level 1",
        "Klettergriffe": "Level 1",
        "Klettergurt": "Sondertaetigkeit",
        "Kletterhelm": "Sondertaetigkeit",
        "Kletterseil": "Sondertaetigkeit",
        "Klettersteigset": "Sondertaetigkeit",
        "Klimmzugstange": "Level 1",
        "Kompass": "Level 1",
        "Komplettgruppe": "Level 1",
        "Kraftstation + Gym Rack": "Level 1",
        "Kühlbox": "Level 1",
        "Kühlbox Zubehör": "Level 1",
        "Langlaufbindung": "Level 1",
        "Langlaufschuhe": "Level 1",
        "Langlaufski": "Level 1",
        "Laufband": "Level 1",
        "Laufrad": "Level 1",
        "Laufrad Zubehör": "Level 1",
        "Laufräder": "Level 1",
        "Lawinensonde": "Level 1",
        "Leichtathletik": "Level 1",
        "Lenker": "Level 1",
        "Lenkerband": "Level 1",
        "Liegestützgriffe": "Level 1",
        "LVS": "Level 6",
        "Meditationskissen": "Level 1",
        "Medizinball": "Level 1",
        "Mountainbike": "Level 1",
        "Nabe + Freilauf": "Level 1",
        "Nachtsichtgerät": "Level 4",
        "Neoprenanzug": "Level 1",
        "Occasion Velo": "Level 1",
        "Okular": "Level 1",
        "Paddel": "Level 1",
        "Padelball": "Level 1",
        "Padelschläger": "Level 1",
        "Pferdebeinschutz": "Level 1",
        "Pferdedecke": "Level 1",
        "Pferdeputzzeug": "Level 1",
        "Pickleball": "Level 1",
        "Picknickdecke": "Level 1",
        "Picknickkorb": "Level 1",
        "Protektoren": "Level 1",
        "Reiterbedarf": "Level 1",
        "Reitsattel": "Level 1",
        "Rennrad": "Level 1",
        "Rollentrainer": "Level 1",
        "Rollschuhe": "Level 1",
        "Rucksack Zubehör": "Level 1",
        "Rudergerät": "Level 1",
        "Sattelstütze": "Level 1",
        "Schalthebel + Bremshebel": "Level 1",
        "Schaltkabel + Bremskabel": "Level 1",
        "Schaltwerk": "Level 1",
        "Scheibenbremse": "Level 1",
        "Schienbeinschoner": "Level 1",
        "Schlafsack": "Level 1",
        "Schlafsack Zubehör": "Level 1",
        "Schlauchboot": "Sondertaetigkeit",
        "Schlingentrainer": "Level 1",
        "Schlitten Zubehör": "Level 1",
        "Schlittschuhe": "Level 1",
        "Schlittschuhe Zubehör": "Level 1",
        "Schneeschuhe": "Level 1",
        "Schnorchelausrüstung": "Level 1",
        "Schuhplatten": "Level 1",
        "Schutzblech": "Level 1",
        "Schwimmausrüstung": "Level 1",
        "Schwimmbad Ausstattung": "Level 1",
        "Schwimmbrille": "Level 1",
        "Schwimmhilfe": "Level 1",
        "Schwimmweste": "Level 1",
        "Scooter": "Level 1",
        "Scooter Zubehör": "Level 1",
        "Seilrolle": "Level 1",
        "Sicherungsgerät": "Sondertaetigkeit",
        "Skateboard": "Level 1",
        "Skateboard Achsen": "Level 1",
        "Skateboard Deck": "Level 1",
        "Skateboard Rollen": "Level 1",
        "Skateboard Zubehör": "Level 1",
        "Ski": "Level 1",
        "Skibindung": "Level 1",
        "Skibrille": "Level 1",
        "Skibrille Zubehör": "Level 1",
        "Skihelm": "Sondertaetigkeit",
        "Skischuhe": "Level 1",
        "Skistöcke": "Level 1",
        "Skitasche + Snowboardtasche": "Level 1",
        "Skiwachs": "Level 1",
        "Skiwerkzeug": "Level 1",
        "Snowboard": "Level 1",
        "Snowboardbindung": "Level 1",
        "Snowboardschuhe": "Level 1",
        "Speedminton": "Level 1",
        "Spikes + Grödel": "Level 1",
        "Sportbrille": "Level 1",
        "Sportschiessen": "Level 1",
        "Springseil": "Level 1",
        "Squashball": "Level 1",
        "Squashschläger": "Level 1",
        "Stalleinrichtung": "Level 1",
        "Stand Up Paddle": "Level 1",
        "Steigeisen": "Level 1",
        "Steppbrett": "Level 1",
        "Steuersatz": "Level 1",
        "Stirnlampe": "Level 1",
        "Stirnlampe Zubehör": "Level 1",
        "Stöcke Zubehör": "Level 1",
        "Studio Kraftgerät": "Level 1",
        "Surfboard": "Level 1",
        "Tauchausrüstung": "Sondertaetigkeit",
        "Taucherbrille": "Level 1",
        "Tauchflasche": "Sondertaetigkeit",
        "Teleskop": "Level 1",
        "Tennisball": "Level 1",
        "Tennisschläger": "Level 1",
        "Tennistasche": "Level 1",
        "Tischtennisbelag": "Level 1",
        "Tischtennisholz": "Level 1",
        "Tischtennisnetz": "Level 1",
        "Tischtennisschläger": "Level 1",
        "Tischtennistisch": "Level 1",
        "Tor": "Level 1",
        "Torwarthandschuhe": "Level 1",
        "Tourenfell Zubehör": "Level 1",
        "Tourenfelle": "Level 1",
        "Tretlager": "Level 1",
        "Trinkflasche + Thermosflasche": "Sondertaetigkeit",
        "Trinkflasche Zubehör": "Level 1",
        "Turngerät": "Level 1",
        "Unihockeyball": "Level 1",
        "Unihockeystock": "Level 1",
        "Velo Montageständer": "Level 1",
        "Veloanhänger": "Level 1",
        "Veloanhänger Zubehör": "Level 1",
        "Veloaufbewahrung": "Level 1",
        "Velocomputer": "Level 4",
        "Velocomputer Zubehör": "Level 4",
        "Velodämpfer": "Level 1",
        "Velofaltwerkzeug": "Level 1",
        "Velofelge": "Level 1",
        "Velogabel": "Level 1",
        "Velogepäck Zubehör": "Level 1",
        "Veloglocke": "Level 1",
        "Velogriff": "Level 1",
        "Velohelm": "Sondertaetigkeit",
        "Velohelm Zubehör": "Level 1",
        "Velokassette": "Level 1",
        "Velokette": "Level 1",
        "Velokindersitz": "Sondertaetigkeit",
        "Velokindersitz Zubehör": "Level 1",
        "Velokoffer": "Level 1",
        "Velokorb": "Level 1",
        "Velokurbel": "Level 1",
        "Velolicht": "Level 1",
        "Velolicht Zubehör": "Level 1",
        "Velopedale": "Level 1",
        "Velopumpe": "Level 1",
        "Velopumpe Zubehör": "Level 1",
        "Velorad Zubehör": "Level 1",
        "Velorahmen": "Level 1",
        "Velorahmen Zubehör": "Level 1",
        "Veloreifen": "Level 1",
        "Veloreifen Zubehör": "Level 1",
        "Veloreinigung + Velopflege": "Level 1",
        "Velosattel": "Level 1",
        "Velosattel Zubehör": "Level 1",
        "Veloschlauch": "Level 1",
        "Veloschloss": "Level 1",
        "Veloschloss Zubehör": "Level 1",
        "Veloständer": "Level 1",
        "Velotasche": "Level 1",
        "Veloträger": "Level 1",
        "Veloträger Zubehör": "Level 1",
        "Velowerkzeug": "Level 1",
        "Vibrationsplatte": "Level 1",
        "Volleybälle": "Level 1",
        "Vorbau": "Level 1",
        "Wakeboard": "Level 1",
        "Wanderstöcke": "Level 1",
        "Wasseraufbereitung": "Level 1",
        "Wassersack": "Level 1",
        "Wasserski": "Level 1",
        "Wildkamera": "Level 4",
        "Yogamatte": "Level 1",
        "Zaumzeug": "Level 1",
        "Zelt": "Level 1",
        "Zelt Zubehör": "Level 1",
        "Zubehör Badminton": "Level 1",
        "Zubehör Ballsport": "Level 1",
        "Zubehör Boote": "Level 1",
        "Zubehör E-Mobility": "Level 1",
        "Zubehör Eishockey": "Level 1",
        "Zubehör Fitness": "Level 1",
        "Zubehör Fitnessgeräte": "Level 1",
        "Zubehör Golf": "Level 1",
        "Zubehör Hanteln": "Level 1",
        "Zubehör Klettern": "Level 1",
        "Zubehör Padel": "Level 1",
        "Zubehör Running": "Level 1",
        "Zubehör Schaltung + Antrieb": "Level 1",
        "Zubehör Sport Optics": "Level 1",
        "Zubehör Squash": "Level 1",
        "Zubehör Surfen": "Level 1",
        "Zubehör Tennis": "Level 1",
        "Zubehör Tischtennis": "Level 1",
        "Zubehör Unihockey": "Level 1",
        "Zubehör Velobremsen": "Level 1",
        "Zubehör Velofederung": "Level 1",
        "Zubehör Velolenkung": "Level 1",
        "Zubehör Wasserski + Wakeboard": "Level 1",
        "Zubehör Yoga + Pilates": "Level 1",
        "Zughilfen": "Level 1",
        "Zusatzgewicht": "Level 1",
        "Agility": "Level 1",
        "Aquarium": "Level 1",
        "Aquarium Dekoration": "Level 1",
        "Aquarium Filter": "Level 1",
        "Aquarium Pflege": "Level 1",
        "Aquariumbeleuchtung": "Level 1",
        "Aquariumtechnik": "Level 1",
        "Einstreu": "Level 1",
        "Fischfutter": "OVP",
        "Futternapf": "Level 1",
        "Futternapf Zubehör": "Level 1",
        "Halsband + Leine": "Level 1",
        "Hundebekleidung": "Level 1",
        "Hundebett + Katzenbett": "Level 1",
        "Hundefutter": "OVP",
        "Hundehütte": "Level 1",
        "Hundespielzeug": "Level 1",
        "Katzenbaum": "Level 1",
        "Katzenfutter": "OVP",
        "Katzenhaus": "Level 1",
        "Katzenklo": "Level 1",
        "Katzenklo Zubehör": "Level 1",
        "Katzenspielzeug": "Level 1",
        "Katzenstreu": "OVP",
        "Katzentüre + Katzennetz": "Level 1",
        "Kleintierstalleinrichtung": "Level 1",
        "Nagerfutter": "OVP",
        "Pferdefutter": "OVP",
        "Reptilienfutter": "OVP",
        "Terrarium": "Level 1",
        "Terrariumbeleuchtung": "Level 1",
        "Terrariumeinrichtung": "Level 1",
        "Terrariumtechnik": "Level 1",
        "Tiergesundheit": "Level 1",
        "Tierhygiene": "Level 1",
        "Tierpflegegerät": "Sondertaetigkeit",
        "Tiertransport": "Level 1",
        "Vogelfutter": "OVP",
        "Vogelhaus": "Level 1",
        "Vogelheimeinrichtung": "Level 1",
        "Vogelkäfig + Voliere": "Level 1",
        "Anstecknadel": "Level 1",
        "Armbanduhr": "Level 1",
        "Armbanduhr Zubehör": "Level 1",
        "Armschmuck": "Level 1",
        "Fussschmuck": "Level 1",
        "Halsschmuck": "Level 1",
        "Kettenanhänger": "Level 1",
        "Manschettenknöpfe": "Level 1",
        "Ohrringe": "Sondertaetigkeit",
        "Piercing": "Sondertaetigkeit",
        "Ring": "Level 1",
        "Schmuck Set": "Level 1",
        "Schmuckdesign": "Level 1",
        "Uhrenbox + Schmuckaufbewahrung": "Level 1",
        "Aktenschrank": "Level 1",
        "Aufbewahrungsbox": "Level 1",
        "Aufbewahrungskorb": "Level 1",
        "Babybett": "Level 1",
        "Babydecke": "Level 1",
        "Babyerinnerungen": "Level 1",
        "Babyhängematte": "Level 1",
        "Babylammfell": "Level 1",
        "Babymatratze": "Sondertaetigkeit",
        "Babymobile": "Level 1",
        "Babynest": "Level 1",
        "Babyschlafsack": "Level 1",
        "Babywippe": "Level 1",
        "Badaufbewahrung": "Level 1",
        "Bademantel": "Level 1",
        "Badeponcho": "Level 1",
        "Badewanneneinlage": "Level 1",
        "Badezimmerregal": "Level 1",
        "Badezimmerschrank": "Level 1",
        "Badteppich": "Level 1",
        "Baldachin": "Level 1",
        "Barhocker": "Level 1",
        "Bartisch": "Level 1",
        "Beistellbett": "Level 1",
        "Bett": "Level 1",
        "Bett Zubehör": "Level 1",
        "Bettgitter": "Level 1",
        "Bettwäsche": "Level 1",
        "Bilder": "Level 1",
        "Bilderrahmen": "Level 4",
        "Bodenschutzmatte": "Level 1",
        "Boxspringbett": "Level 1",
        "Buchstütze": "Level 1",
        "Bürostuhl": "Level 1",
        "Christbaumschmuck": "Level 1",
        "Christbaumständer Zubehör": "Level 1",
        "Couchtisch + Beistelltisch": "Level 1",
        "Decke": "Level 1",
        "Deko Aufhänger": "Level 1",
        "Deko Figuren + Skulpturen": "Level 1",
        "Deko Schriftzug": "Level 1",
        "Deko Schwerter": "Level 1",
        "Dekofolie": "Level 1",
        "Dekokissen": "Level 1",
        "Objektkonverter": "Level 1",
        "Dekokranz": "Level 1",
        "Dekoschale": "Level 1",
        "Duftkerzen": "Level 1",
        "Duschablage": "Level 1",
        "Duschabzieher": "Level 1",
        "Duschvorhang": "Level 1",
        "Duschvorhangstange": "Level 1",
        "Duvet": "Level 1",
        "Elektrokamin + Bioethanolkamin": "Level 1",
        "Essgruppe": "Level 1",
        "Esstisch": "Level 1",
        "Fassadenbeleuchtung": "Level 1",
        "Fell": "Level 1",
        "Fensterfolie": "Level 1",
        "Fixleintuch": "Level 1",
        "Fixleintuch Babybett": "Level 1",
        "Fotoalbum": "Level 1"
    };
